-- MySQL Script generated by MySQL Workbench
-- Sat 10 Oct 2015 11:43:35 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ventamatic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ventamatic` ;

-- -----------------------------------------------------
-- Schema ventamatic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventamatic` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ventamatic` ;

-- -----------------------------------------------------
-- Table `ventamatic`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`states` (
  `id` CHAR(2) NOT NULL COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `short` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`municipalities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`municipalities` (
  `id` CHAR(3) NOT NULL COMMENT '',
  `state_id` CHAR(2) NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `state_id`)  COMMENT '',
  INDEX `fk_municipality_state_idx` (`state_id` ASC)  COMMENT '',
  CONSTRAINT `fk_municipality_state`
    FOREIGN KEY (`state_id`)
    REFERENCES `ventamatic`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`localities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`localities` (
  `id` CHAR(4) NOT NULL COMMENT '',
  `municipality_id` CHAR(3) NOT NULL COMMENT '',
  `state_id` CHAR(2) NOT NULL COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`id`, `municipality_id`, `state_id`)  COMMENT '',
  INDEX `fk_locality_municipality_idx` (`municipality_id` ASC)  COMMENT '',
  INDEX `fk_locality_state_idx` (`state_id` ASC)  COMMENT '',
  CONSTRAINT `fk_locality_municipality`
    FOREIGN KEY (`municipality_id`)
    REFERENCES `ventamatic`.`municipalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locality_state`
    FOREIGN KEY (`state_id`)
    REFERENCES `ventamatic`.`municipalities` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NOT NULL COMMENT '',
  `cell_phone` VARCHAR(45) NULL COMMENT '',
  `adress` VARCHAR(100) NULL COMMENT '',
  `email` VARCHAR(200) NULL COMMENT '',
  `rfc` VARCHAR(20) NULL COMMENT '',
  `locality_id` CHAR(4) NULL COMMENT '',
  `municipality_id` CHAR(3) NULL COMMENT '',
  `state_id` CHAR(2) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  `password` VARCHAR(60) NULL COMMENT '',
  `remember_token` VARCHAR(100) NULL COMMENT '',
  `userscol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC)  COMMENT '',
  INDEX `fk_client_locality_idx` (`locality_id` ASC)  COMMENT '',
  INDEX `fk_client_municipality_idx` (`municipality_id` ASC)  COMMENT '',
  INDEX `fk_client_state_idx` (`state_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_locality`
    FOREIGN KEY (`locality_id`)
    REFERENCES `ventamatic`.`localities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_municipality`
    FOREIGN KEY (`municipality_id`)
    REFERENCES `ventamatic`.`localities` (`municipality_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_state`
    FOREIGN KEY (`state_id`)
    REFERENCES `ventamatic`.`localities` (`state_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`branches` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `ticket_name` VARCHAR(60) NULL COMMENT '',
  `ticket_head` VARCHAR(255) NULL COMMENT '',
  `ticket_foot` VARCHAR(255) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`shift_works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`shift_works` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '',
  `status` ENUM('A','F') NOT NULL DEFAULT 'A' COMMENT 'A= Active\nF= Finished',
  `initial` DECIMAL(10,2) NULL COMMENT '',
  `final` DECIMAL(10,2) NULL COMMENT '',
  `calculed` DECIMAL(10,2) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_innings_branch_idx` (`branch_id` ASC)  COMMENT '',
  INDEX `fk_innings_user_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_innings_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `ventamatic`.`branches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_innings_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ventamatic`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`user` (
  `username` VARCHAR(16) NOT NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `password` VARCHAR(32) NOT NULL COMMENT '',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '');


-- -----------------------------------------------------
-- Table `ventamatic`.`buys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`buys` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `provider_id` INT UNSIGNED NOT NULL COMMENT '',
  `total` DECIMAL(10,2) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_buys_branch_idx` (`branch_id` ASC)  COMMENT '',
  INDEX `fk_buys_user_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_buys_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `ventamatic`.`branches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buys_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ventamatic`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_buys_provider`
    FOREIGN KEY ()
    REFERENCES `ventamatic`.`user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `category_id` INT UNSIGNED NOT NULL COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `minimum` INT UNSIGNED NULL COMMENT '',
  `unit` ENUM('U','KG', 'L') NOT NULL COMMENT 'U=Unit\nKG=kilograms\nL=liter',
  `bar_code` VARCHAR(50) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  UNIQUE INDEX `bar_code_UNIQUE` (`bar_code` ASC)  COMMENT '',
  INDEX `fk_product_category_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `ventamatic`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`branch_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`branch_product` (
  `branch_id` INT UNSIGNED NOT NULL COMMENT '',
  `product_id` INT UNSIGNED NOT NULL COMMENT '',
  `stock` DECIMAL(10,3) UNSIGNED NULL DEFAULT 0 COMMENT '',
  `price` DECIMAL(10,3) UNSIGNED NULL COMMENT '',
  `cost` DECIMAL(10,3) UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`branch_id`, `product_id`)  COMMENT '',
  INDEX `fk_branch_product_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_branch_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `ventamatic`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `ventamatic`.`branches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`branch_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`branch_user` (
  `branch_id` INT UNSIGNED NOT NULL COMMENT '	',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`branch_id`, `user_id`)  COMMENT '',
  INDEX `fk_branch_user_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_branch_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ventamatic`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `ventamatic`.`branches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`sales` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `branch_id` INT UNSIGNED NOT NULL COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `client_id` INT UNSIGNED NOT NULL COMMENT '',
  `total` DECIMAL(10,2) NOT NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  `deleted_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_buys_branch_idx` (`branch_id` ASC)  COMMENT '',
  INDEX `fk_buys_user_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_sales_client_idx` (`client_id` ASC)  COMMENT '',
  CONSTRAINT `fk_sale_branch`
    FOREIGN KEY (`branch_id`)
    REFERENCES `ventamatic`.`branches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ventamatic`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `ventamatic`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`buy_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`buy_product` (
  `buy_id` INT UNSIGNED NOT NULL COMMENT '',
  `product_id` INT UNSIGNED NOT NULL COMMENT '',
  `quantity` INT UNSIGNED NULL COMMENT '',
  `cost` DECIMAL(10,2) UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`buy_id`, `product_id`)  COMMENT '',
  INDEX `fk_buy_product_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_buy_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `ventamatic`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_buy`
    FOREIGN KEY (`buy_id`)
    REFERENCES `ventamatic`.`buys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`product_sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`product_sale` (
  `sale_id` INT UNSIGNED NOT NULL COMMENT '',
  `product_id` INT UNSIGNED NOT NULL COMMENT '',
  `quantity` INT UNSIGNED NULL COMMENT '',
  `price` DECIMAL(10,2) UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`sale_id`, `product_id`)  COMMENT '',
  INDEX `fk_buy_product_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_sale_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `ventamatic`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_sale`
    FOREIGN KEY (`sale_id`)
    REFERENCES `ventamatic`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventamatic`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`category` (
  `category_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`category_id`)  COMMENT '');


-- -----------------------------------------------------
-- Table `ventamatic`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP NULL COMMENT '');


-- -----------------------------------------------------
-- Table `ventamatic`.`timestamps_1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventamatic`.`timestamps_1` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `update_time` TIMESTAMP NULL COMMENT '');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
